### ISSUE TITLE
opd/0xec11 does not work.

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil-icon-font#17]
When using the `opd/0xec11` icon, it is not being displayed (which normally indicates that the glyph is not present). This might be a weird bug due to being last in the list.

**Comment by nathakits** [comment]
I see the icon in the master SVG file and also in the master .tff file in --> https://github.com/pupil-labs/pupil-icon-font/tree/master/font

Not sure why it is not being displayed. I will try and debug this in pyglui.

**Comment by nathakits** [comment]
@papr - I figured out the issue. The problem is that this that the encoding of the last icon `opd` is incorrect. It is `ec12` here but should actually be `ec11`. I will make a PR for the latest updated icon font to pyglui.

**Comment by nathakits** [comment]
@papr @willpatera PR for the latest icon font - https://github.com/pupil-labs/pyglui/pull/58

**Comment by nathakits** [comment]
PR has been merged. This should fix it.

**Comment by willpatera** [comment]
Not fixed - let's manually generate the icon font and work out bugs in the icon font scripts after new icons are added and merged with pyglui/pupil.
